routes:
  - route:
      url: '/index'
      action: 'index'
      controller: 'AppController'
      vars:
        - maVariable: 'data'
  - route:
      url: '/test'
      action: 'test'
      controller: 'AppController'
      vars:
        - maVariable: 'data'